# Generated by Django 6.0.6 on 2026-06-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repeat_days', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('xp', models.IntegerField(default=10)),
            ],
        ),
    ]
